// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_PRINT_CLUSTER
#define SILABS_PRINT_CLUSTER


// This is the mapping of IDs to cluster names assuming a format according
// to the "sl_zigbee_af_cluster_name_t" defined in the ZCL header.
// The names of clusters that are not present, are removed.

  #define SILABS_PRINTCLUSTER_BASIC_CLUSTER { ZCL_BASIC_CLUSTER_ID, 0x0000, "Basic" },
  #define SILABS_PRINTCLUSTER_OCCUPANCY_SENSING_CLUSTER { ZCL_OCCUPANCY_SENSING_CLUSTER_ID, 0x0000, "Occupancy Sensing" },

#define CLUSTER_IDS_TO_NAMES \
  SILABS_PRINTCLUSTER_BASIC_CLUSTER \
  SILABS_PRINTCLUSTER_OCCUPANCY_SENSING_CLUSTER \

#endif // SILABS_PRINT_CLUSTER
